language: "perl"

env:
  - ELASTICSEARCH_VERSION=6.3.1 ES_HOME=$HOME/elasticsearch/$ELASTICSEARCH_VERSION/

perl:
  - "5.16"

before_install:
    - echo 'grant { permission javax.management.MBeanTrustPermission "register"; };' | sudo tee -a $JAVA_HOME/jre/lib/security/java.policy
    - bash ./travisci/install_elasticsearch.sh
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl.git
    - git clone --branch master --depth 1 https://github.com/EnsemblGenomes/ensemblgenomes-api.git
    - git clone -b release-1-6-924 --depth 1 https://github.com/bioperl/bioperl-live.git
    - pip install --user jsonschema

install:
    - cpanm -n Module::Install::Catalyst
    - cpanm -n Devel::Cover::Report::Coveralls
    - cpanm --installdeps --with-recommends --notest $PWD/src/Registry

before_script:
    - sleep 10

script: "./travisci/harness.sh"

cache:
  directories:
    - $HOME/elasticsearch
    - $HOME/perl5

notifications:
  email:
    on_success: always
    on_failure: always
