language: "perl"

perl:
  - "5.16"

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.3.1.deb
  - sudo dpkg -i --force-confnew elasticsearch-6.3.1.deb
  - sudo service elasticsearch restart
  - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl.git
  - git clone --branch master --depth 1 https://github.com/EnsemblGenomes/ensemblgenomes-api.git
  - git clone -b release-1-6-924 --depth 1 https://github.com/bioperl/bioperl-live.git
  - pip install --user jsonschema

install:
  - cpanm -n Module::Install::Catalyst
  - cpanm -n Devel::Cover::Report::Coveralls
  - cpanm --installdeps --with-recommends --notest $PWD/src/Registry

script: "./travisci/harness.sh"

cache:
  directories:
    - $HOME/perl5

notifications:
  email:
    on_success: always
    on_failure: always
