package Registry::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Registry::Schema',
    
    connect_info => {
        dsn => 'dbi:SQLite:registry.db',
        user => '',
        password => '',
    }
);

=head1 NAME

Registry::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Registry>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Registry::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

Premanand Achuthan

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
