package Registry::Model::GenomeAssemblyDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Registry::GenomeAssembly::Schema',
    
    
);

=head1 NAME

Registry::Model::GenomeAssemblyDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Registry>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Registry::GenomeAssembly::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

Alessandro

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
